version: '3'
services:
    switws:
        container_name: switws
        image: marcarlo/switwspy:2
        volumes:
            - $PWD/switws/ws:/srv                             # Webservice and forms 
            - $PWD/switws/ws/config:/etc/switws/config:ro     # Configuration files
            - /tmp/_switcache_:/srv/__pycache__
        environment:
            AIS_POSTGRES_PASSWORD: $AIS_USER_PASSWORD
            SCINTILLATION_POSTGRES_PASSWORD: $SCINT_USER_PASSWORD
            TECDB_POSTGRES_PASSWORD: $TECDB_USER_PASSWORD
            HFF_POSTGRES_PASSWORD: $HFF_USER_PASSWORD
        ports:
            - '8080:5000'
        networks:
            default:
                ipv4_address: 172.18.10.102
        logging:
            driver: syslog
            options:
                tag: "swit_switws"
        depends_on:
            - wscache
        restart: always

    wscache:
        container_name: wscache
        image: redis:6.2-alpine
        networks:
            default:
        #        ipv4_address: 172.18.1.101
        volumes:
            - $REDIS_DATASTORAGE:/data/redis
        logging:
            driver: syslog
            options:
                tag: "swit_wscache"
        command: redis-server --loglevel verbose
        restart: always
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.10.0/24
