CREATE USER grafana WITH PASSWORD '$GRAFANA_PASS';
GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

CREATE USER aisu WITH PASSWORD '$AISU_PASS';
CREATE DATABASE ais OWNER aisu;
GRANT ALL PRIVILEGES ON DATABASE ais TO aisu;

CREATE USER wsreader WITH PASSWORD '$WSREADER_AIS_PASS';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO wsreader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO wsreader;
