CREATE USER grafana WITH PASSWORD '$GRAFANA_PASS';
GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

CREATE USER scintu WITH PASSWORD '$SCINTU_PASS';
CREATE DATABASE scint OWNER scintu;
GRANT ALL PRIVILEGES ON DATABASE scint TO scintu;

CREATE USER wsreader WITH PASSWORD '$WSREADER_SCINT_PASS';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO wsreader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO wsreader;
