CREATE USER tecu WITH PASSWORD '$TECU_PASS';
CREATE DATABASE tecdb OWNER tecu;
GRANT ALL PRIVILEGES ON DATABASE tecdb TO tecu;

CREATE USER grafana WITH PASSWORD '$GRAFANA_PASS';
GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

CREATE USER wsreader WITH PASSWORD '$WSREADER_TECDB_PASS';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO wsreader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO wsreader;

