-- CREATE USER grafana WITH PASSWORD '$GRAFANA_PASS';
GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

-- CREATE USER wsreader WITH PASSWORD '$WSREADER_PASS';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO wsreader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO wsreader;
ALTER DEFAULT PRIVILEGES FOR ROLE tecu IN SCHEMA public GRANT SELECT ON TABLES TO wsreader;

