version: '3'
services:
    iparser_tec:
        container_name: iparser_tec
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/tec_json:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "switdb.rm.ingv.it"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_tec"
        networks:
            - default
        restart: always

    iparser_ais:
        container_name: iparser_ais
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/ais:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "switdb.rm.ingv.it"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_ais"
        networks:
            - default
        restart: always

    iparser_scint:
        container_name: iparser_scint
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/scint:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "switdb.rm.ingv.it"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_scint"
        networks:
            - default
        restart: always

    iparser_hermes:
        container_name: iparser_hermes
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/hermes:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "switdb.rm.ingv.it"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_hermes"
        networks:
            - default
        restart: always

    iparser_hf:
        container_name: iparser_hf
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/swesnet_hf:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "switdb.rm.ingv.it"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_hf"
        networks:
            - default
        restart: always

    iparser_man:
        container_name: iparser_man
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/man:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "switdb.rm.ingv.it"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_man"
        networks:
            - default
        restart: always

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
