services:
    datapg:
        container_name: datapg
        image: "timescale/timescaledb:latest-pg14"
        volumes:
            - $DEPLOYHOME/data/datadir_datapg:/var/lib/postgresql/data
            - /tmp/datapg:/tmp
        environment:
            POSTGRES_PASSWORD: $DATAPG_POSTGRES_PASS
        logging:
            driver: syslog
            options:
                tag: "swit_datapg"
        ports:
            - "5432:5432"
        networks:
            - default
        restart: always
    

    iparser_tec:
        container_name: iparser_tec
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/tec_json:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_tec"
        networks:
            - default
        restart: always

    iparser_ais:
        container_name: iparser_ais
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/ais:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_ais"
        networks:
            - default
        restart: always

    iparser_scint:
        container_name: iparser_scint
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/scint:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_scint"
        networks:
            - default
        restart: always

    iparser_hermes:
        container_name: iparser_hermes
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/hermes:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_hermes"
        networks:
            - default
        restart: always

    iparser_hf:
        container_name: iparser_hf
        image: marcarlo/ionoparser:v4
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/swesnet_hf:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_hf"
        networks:
            - default
        restart: always

    switws:
        container_name: switws
        image: ingv-switws:1.0
        environment:
            AIS_POSTGRES_PASSWORD: $AIS_USER_PASSWORD
            SCINTILLATION_POSTGRES_PASSWORD: $SCINT_USER_PASSWORD
            TECDB_POSTGRES_PASSWORD: $TECDB_USER_PASSWORD
            HFF_POSTGRES_PASSWORD: $HFF_USER_PASSWORD
        ports:
            - '8080:5000'
        networks:
            default:
                ipv4_address: 172.18.1.102
        logging:
            driver: syslog
            options:
                tag: "swit_switws"
        depends_on:
            - wscache
        restart: always

    wscache:
        container_name: wscache
        image: redis:6.2-alpine
        networks:
            default:
        #        ipv4_address: 172.18.1.101
        volumes:
            - $REDIS_DATASTORAGE:/data/redis
        logging:
            driver: syslog
            options:
                tag: "swit_wscache"
        command: redis-server --loglevel verbose
        restart: always
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
