# version: '3'
services:
    datapg:
        container_name: datapg
        image: "postgres:12.2"
        volumes:
            - $DEPLOYHOME/data/datadir_datapg:/var/lib/postgresql/data
            - /tmp/datapg:/tmp
        environment:
            POSTGRES_PASSWORD: $DATAPG_POSTGRES_PASSWORD
        logging:
            driver: syslog
            options:
                tag: "swit_datapg"
        ports:
            - "5432:5432"
        networks:
            - default
        restart: always
    
    scintdb:
        container_name: scintdb
        image: "timescale/timescaledb:latest-pg14"
        volumes:
            - $DEPLOYHOME/data/data_scintdb:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: $SCINTDB_POSTGRES_PASSWORD
        logging:
            driver: syslog
            options:
                tag: "swit_scintdb"
        ports:
            - "5434:5432"
        networks:
            - default
        restart: always

    aispg:
        container_name: aispg
        image: "postgres:12.2"
        volumes:
            - $DEPLOYHOME/data/datadir_aispg:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: $AISPG_POSTGRES_PASSWORD
        logging:
            driver: syslog
            options:
                tag: "swit_aispg"
        ports:
            - "5433:5432"
        networks:
            - default
        restart: always
    
    iparser_tec:
        container_name: iparser_tec
        image: marcarlo/ionoparser:v3
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/tec_json:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_tec"
        networks:
            - default
        restart: always

    iparser_ais:
        container_name: iparser_ais
        image: marcarlo/ionoparser:v3
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/ais:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_ais"
        networks:
            - default
        restart: always

    iparser_scint:
        container_name: iparser_scint
        image: marcarlo/ionoparser:v3
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/scint:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_scint"
        networks:
            - default
        restart: always

    iparser_hermes:
        container_name: iparser_hermes
        image: marcarlo/ionoparser:v3
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/hermes:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_hermes"
        networks:
            - default
        restart: always

    iparser_hf:
        container_name: iparser_hf
        image: marcarlo/ionoparser:v3
        volumes:
            - $PWD/ionoparser:/app
            - $DEPLOYHOME/input/swesnet_hf:/data
            - $DEPLOYHOME/$DEFAULTBKDIR:/backup
        environment:
            IPARSER_SWIT_HOST: "datapg"
            IPARSER_SWIT_PORT: "5432"
            IPARSER_SWIT_DB: "swit"
            IPARSER_SWIT_USER: "switu"
            IPARSER_SWIT_PASS: $SWITU_PASS
        working_dir: /app
        stdin_open: true
        tty: true        
        logging:
           driver: syslog
           options:
                tag: "swit_iparser_hf"
        networks:
            - default
        restart: always

    switws:
        container_name: switws
        image: marcarlo/switws:1.0.0
        volumes:
            - $PWD/switws/ws/config:/etc/switws/config:ro     # Configuration files
            - /tmp/_switcache_:/srv/__pycache__
        environment:
            AIS_POSTGRES_PASSWORD: $WSREADER_AIS_PASSWORD 
            SCINT_POSTGRES_PASSWORD: $WSREADER_SCINT_PASSWORD
            TEC_POSTGRES_PASSWORD: $WSREADER_TECDB_PASSWORD
            HFF_POSTGRES_PASSWORD: $WSREADER_GRID_PASSWORD
        ports:
            - '8080:5000'
        networks:
            default:
                ipv4_address: 172.18.1.100
        logging:
            driver: syslog
            options:
                tag: "swit_switws"
        depends_on:
            - wscache
        restart: always

    wscache:
        container_name: wscache
        image: redis:6.2-alpine
        networks:
            default:
        #        ipv4_address: 172.18.1.101
        volumes:
            - $DEPLOYHOME/data/redis:/data/redis
        logging:
            driver: syslog
            options:
                tag: "swit_wscache"
        command: redis-server --loglevel verbose
        restart: always

    wwwconfig:
        container_name: wwwconfig
        image: webdevops/php-apache
        volumes:
            - $PWD/webstation/html:/var/www/html
        environment:
            WSREADER_AIS_PASSWORD: $WSREADER_AIS_PASSWORD
            WSREADER_SCINT_PASSWORD: $WSREADER_SCINT_PASSWORD
            WSREADER_TECDB_PASSWORD: $WSREADER_TECDB_PASSWORD

        ports:
            - "80:80"
        logging:
           driver: syslog
           options:
                tag: "swit_wwwconfig"
        networks:
            - default
        restart: always

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
