# WS Configuration file

# Set the timeout (in seconds)
timeout: 60

# Set the maximum number of requests per minute (per worker), if the filed is none or not provided the Middleware will not be activated
requests_per_minute: 120

# Define the number of workers, if the field is none or not provided it will be calculated on the server availability
# workers: 10

# Define the loglevel of access_logs (fields allowed: 'debug', 'info', 'warning', 'error', 'critical')
loglevel: 'info'

# Define CORS origins allowed
cors_allowed: 
    - '*'

# Define the format of datetime responses
datetime_format: '%Y-%m-%d %H:%M:%S'

# Set to True if jsonb fields need to be converted into string
jsonb_to_string: true

# Set the configuration for the cache (default NullCache)
cache_config:
    CACHE_TYPE: "RedisCache"
    CACHE_DEFAULT_TIMEOUT: 300
    CACHE_REDIS_HOST: "wscache"
    CACHE_REDIS_PORT: 6379
    CACHE_THRESHOLD: 100
